### ISSUE TITLE
Demo Setup: Cannot find a model for Dall-e or one that is "plug-in capable"

### ISSUE THREAD

**Issue by shermes** [microsoft/PodcastCopilot#6]
I have access to Azure Open AI and I am able to deploy models. I created an instance in East US. I was able to deploy gpt4 as per the instructions but I  do not see "dalle and a plugins-capable model." I looked at the list of models and nothing here helped me understand which model to choose. Am I in the wrong region or is there some step I missed? 

List of Models: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models#model-summary-table-and-region-availability

Do any of these models generate images or support plug-ins?
<img width="620" alt="image" src="https://github.com/microsoft/PodcastCopilot/assets/8727388/7b24761a-3541-4e61-bc18-20102ef31166">

**Comment by jennifermarsman** [comment]
The DALL-E models are still in private preview.  For the DALL-E model, you must request access using the form at https://aka.ms/oai/access and in question #22, request access to the DALL-E models for image generation.  

The plugin-capable models are not publicly released yet.

**Comment by jennifermarsman** [comment]
I've updated the README with this information in this commit: https://github.com/microsoft/PodcastCopilot/commit/56db5b1beaac65b0f8e11c2dd695e2cb21457c56
